out_dir: results
metric_best: mae
metric_agg: argmin
accelerator: "cuda:0"
num_workers: 0
mlflow:
  use: False
  project: peptides-structural
  name: peptides-structural
wandb:
  use: False
  project: peptides-structural
  name: peptides-structural
dataset:
  pe_transform_on_the_fly: True
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RRWP:
  enable: True
  ksteps: 24
  add_identity: True
  add_node_attr: False
  add_uniform: False
  sym_norm: False
  k_hop: -1
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: BaseGraphNet
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: mean
gt:
  pos_enc:
    enable: True
    node_encoder:
      enable: True
      raw_norm: 'none'
      post_norm: 'none'
      name: 'MLPNodeEncoder+MLPNodeEncoder+MLPNodeEncoder'
      pe_name: 'rrwp+log_deg+log_order'
      in_dim: '25+1+1'
      MLPNodeEncoder:
        post_norm: 'none'
        kaiming_uniform_linear_init: True
    edge_encoder:
      enable: True
      post_norm: 'none'
      raw_norm: 'none'
      name: 'MLPSinEdgeEncoder+EdgeFFN'
      pe_name: 'rrwp+edge'
      in_dim: '25+96'
      MLPSinEdgeEncoder:
        to_complete_graph: True
        sin_L: 3
        hid_dim: '128'
        bias: True
        add_raw_feat: True
        add_invD: True
        add_invN: True
        kaiming_uniform_linear_init: True
        dropout: 0.1
      EdgeFFN:
        pre_mlp_norm: 'ada_rms_norm'
        post_mlp_norm: 'none'
        pre_backbone_norm: 'none'
        post_backbone_norm: 'ada_rms_norm'
        num_blocks: 1
        ffn_ratio: 2
        add_weight_norm: False
        add_spectral_norm: False
        dropout: 0.
        proj_drop: 0.
        drop_path: 0.
        drop_path_scale: True
        act: 'gelu'
  layer_type: PPGTLayer
  layers: 5
  n_heads: 8
  dim_hidden: 96         # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.
  proj_drop: 0.
  drop_path: 0.1
  drop_path_scale: True
  attn_dropout: 0.1
  ffn_ratio: 2
  norm_fn: "ada_rms_norm"
  macro_norm_type: 'pre_norm'
  pre_backbone_norm: 'none'
  post_backbone_norm: 'ada_rms_norm'
  layer_scale: False  # post-norm doesn't need LayerScale
  alpha: 1e-4
  attn:
    qkv_bias: True
    urpe: True
    l2dist: True
    zero_token: False
    learned_scale: False
    gate: False
    deg_scaler: False
    clamp: None
    act: 'gelu'
gnn:
  head: linear_graph_nodecay
  trunc_init: True
  post_pooling_norm: 'none'
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 96             # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: False
  act: 'gelu'
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: timm_adamW
  weight_decay: 1e-5
  base_lr: 7e-4
  max_epoch: 250
  num_warmup_epochs: 10
  scheduler: timm_cosine_with_warmup
  min_lr: 1e-4
